name: CI

on: [push, pull_request]

jobs:
  build_and_test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin

    steps:
      - name: install musl tools
        if: os == "ubuntu-latest"
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-gcc

      - uses: actions/checkout@v3
        name: checkout
        with:
          fetch-depth: 1

      - uses: dtolnay/rust-toolchain@stable
        name: test stable
        with:
          target: ${{ matrix.target }}
        if: target != "aarch64-apple-darwin"
        run: cargo test --target ${{ matrix.target }} --verbose

      - uses: dtolnay/rust-toolchain@nightly
        name: clippy/fmt
        with:
          target: ${{ matrix.target }}
          components: clippy, rustfmt
        run: cargo clippy --target ${{ matrix.target }} -q
        run: cargo fmt -q

      - uses: dtolnay/rust-toolchain@nightly
        name: test nightly
        with:
          target: ${{ matrix.target }}
        if: target != "aarch64-apple-darwin"
        run: cargo test --target ${{ matrix.target }} --verbose
