name: Release

on:
  push:
    tags: [ v* ]

jobs:
  build_and_release:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            ext: ".exe"
            oname: ""
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            ext: ""
            oname: "-linux"
          - os: macos-latest
            target: x86_64-apple-darwin
            ext: ""
            oname: "-darwin"

    steps:
      - uses: actions/checkout@v2
        name: checkout
        with:
          fetch-depth: 1

      - uses: actions-rs/toolchain@v1
        name: setup rust
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
          components: rustfmt, clippy

      - uses: actions-rs/cargo@v1
        name: clippy
        with:
          command: clippy
          args: -q --release

      - uses: actions-rs/cargo@v1
        name: test
        with:
          command: test
          args: --release

      - uses: actions-rs/cargo@v1
        name: fmt
        with:
          command: fmt
          args: -q

      - uses: actions-rs/cargo@v1
        name: release
        with:
          command: build
          args: --verbose --release

      - uses: svenstaro/upload-release-action@v2
        name: Upload binaries to release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: target/release/fse_dump${{ matrix.ext }}
          asset_name: fse_dump-${{ github.ref_name }}${{ matrix.oname }}${{ matrix.ext }}
      
  publish:
    name: Publish
    needs: build_and_release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - uses: katyo/publish-crates@v1
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
