name: Release

on:
  push:
    tags: [ v* ]

jobs:
  build_and_release:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            ext: ".exe"
            oname: ""
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            ext: ""
            oname: "-linux"
          - os: macos-latest
            target: x86_64-apple-darwin
            ext: ""
            oname: "-darwin"
          - os: macos-latest
            target: aarch64-apple-darwin
            ext: ""
            oname: "-darwin_arm64"

    steps:
      - name: install musl tools
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y musl musl-dev musl-tools

      - uses: actions/checkout@v3
        name: checkout
        with:
          fetch-depth: 1

      - uses: dtolnay/rust-toolchain@stable
        name: check and build
        with:
          target: ${{ matrix.target }}
          components: clippy

      - run: cargo clippy --target ${{ matrix.target }} -q --release

      - run: cargo test --target ${{ matrix.target }} --verbose --release
        if: ${{ matrix.target != 'aarch64-apple-darwin' }}

      - run: cargo build --target ${{ matrix.target }} --verbose --release

      - uses: svenstaro/upload-release-action@v2
        name: Upload binaries to release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: target/release/fse_dump${{ matrix.ext }}
          asset_name: fse_dump-${{ github.ref_name }}${{ matrix.oname }}${{ matrix.ext }}

  publish:
    name: Publish
    needs: build_and_release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: katyo/publish-crates@v1
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
